"""The BFGS parity gate: the optimizer registry must not move a single bit.

Slice S1 turned a hardcoded ``opt.minimize(loss, x0, method="BFGS")`` into a
declarable registry with an escalation default. The claim that buys that change
its licence is narrow and checkable: WHERE BFGS MOVED, every number is exactly
what it was. Not close, not within a tolerance that could hide a perturbed
optimizer path: identical, compared as hex float literals.

This is checked in rather than run by hand (PR #108 did it manually and lost the
evidence). ``tests/integrations/llmsr/test_optimizers.py`` runs ``check_all()``
so the gate fires on every test run.

Each case is verified twice over. Once with ``--optimizer bfgs``, whose payload
must equal the golden captured on ``main``. And once with ``auto``, which must
report ``bfgs`` as the optimizer that produced the winner: that is the direct
observation that BFGS DID move here, so these cases genuinely exercise the path
the parity claim is about, and it must land on the same numbers.

The first case reuses the anchor S0b checked in at
``test_progress.py::TestNoPathIsUnchanged`` (a 2-group exp fit, captured on main
at 81d75d1). Its constants are asserted against that anchor rather than
duplicated, so the two cannot drift apart.

Regenerating the golden file, from the repo root (``git archive`` reads the
commit, so it touches no working tree and no sibling worktree)::

    rm -rf /tmp/wheeler-main && mkdir -p /tmp/wheeler-main
    git archive main | tar -x -C /tmp/wheeler-main
    cd /tmp/wheeler-main && PYTHONPATH=/tmp/wheeler-main python \\
        tests/integrations/llmsr/parity_bfgs.py capture > /tmp/golden.json
    cp /tmp/golden.json <repo>/tests/integrations/llmsr/parity_bfgs_golden.json

Then ``python tests/integrations/llmsr/parity_bfgs.py check`` here.
"""

from __future__ import annotations

import inspect
import json
import sys
from pathlib import Path

import numpy as np

from wheeler.integrations.llmsr import fit as fit_mod
from wheeler.integrations.llmsr import metrics as metrics_mod
from wheeler.integrations.llmsr.vendor import code_manipulation, evaluator

HERE = Path(__file__).resolve().parent
FIX = HERE / "fixtures"
GOLDEN = HERE / "parity_bfgs_golden.json"


# ------------------------------------------------------------------- the cases

EXP_BODY = (
    "import numpy as np\n"
    "def equation(x1, params):\n"
    "    return params[0] * np.exp(params[1] * x1) + params[2]\n"
)


def _exp_groups() -> list[tuple[str, np.ndarray, np.ndarray]]:
    """The S0b anchor's data, generated by the same recipe it uses."""
    rng = np.random.default_rng(11)
    out = []
    for name, (a, b, c) in {"g1": (2.0, 0.3, -1.0), "g2": (-1.5, 0.7, 4.0)}.items():
        x = rng.uniform(-1.0, 1.0, 30)
        out.append((name, x.reshape(-1, 1), a * np.exp(b * x) + c))
    return out


def _bactgrow_program() -> str:
    """The shipped fixture spec's seed body, built the way ``init`` builds it."""
    spec_text = (FIX / "spec_bactgrow.txt").read_text()
    template = code_manipulation.text_to_program(spec_text)
    body = template.get_function("equation").body
    _fn, program = evaluator._sample_to_program(body, None, template, "equation")
    return program


def _bactgrow_table() -> tuple[np.ndarray, np.ndarray]:
    """Load the fixture CSV with numpy alone.

    Deliberately not via ``data._load_data``: this script has to run unchanged
    inside a checkout of whatever commit it is comparing against, so it leans
    only on modules that predate the slices being compared.
    """
    table = np.genfromtxt(FIX / "train_small.csv", delimiter=",", skip_header=1)
    return table[:, :-1], table[:, -1].reshape(-1)


def _cases() -> dict[str, dict]:
    """Every parity case: name -> the kwargs ``evaluate_body_grouped`` is given."""
    X, y = _bactgrow_table()
    program = _bactgrow_program()
    even, odd = np.arange(len(y)) % 2 == 0, np.arange(len(y)) % 2 == 1
    return {
        # The S0b anchor: two groups, three real constants inside a budget of ten.
        "exp-2group": {
            "program_str": EXP_BODY,
            "function_to_evolve": "equation",
            "groups": _exp_groups(),
            "metric": metrics_mod.MSE,
        },
        # The shipped fixture spec, four inputs, ten constants, ungrouped.
        "bactgrow-ungrouped": {
            "program_str": program,
            "function_to_evolve": "equation",
            "groups": [(fit_mod.UNGROUPED, X, y)],
            "metric": metrics_mod.MSE,
        },
        # The same spec under the grouped protocol, each group refitting its own
        # constants: the path where one blind group would sink the candidate.
        "bactgrow-2group": {
            "program_str": program,
            "function_to_evolve": "equation",
            "groups": [("even", X[even], y[even]), ("odd", X[odd], y[odd])],
            "metric": metrics_mod.NMSE,
        },
    }


# ------------------------------------------------------------------ the payload

def _hex(value) -> str | None:
    return None if value is None else float(value).hex()


def _payload(result) -> dict:
    """Everything a fit produced, as hex floats: no tolerance, no rounding."""
    return {
        "valid": result.valid,
        "error": result.error,
        "score": _hex(result.score),
        "value": _hex(result.value),
        "per_group": {k: _hex(v) for k, v in sorted(result.per_group.items())},
        "per_group_value": {
            k: _hex(v) for k, v in sorted(result.per_group_value.items())
        },
        "params": [_hex(p) for p in result.params],
        "params_per_group": {
            k: [_hex(p) for p in v] for k, v in sorted(result.params_per_group.items())
        },
    }


def _run(kwargs: dict, optimizer: str | None) -> object:
    """Run one case, asking for ``optimizer`` only where that is a thing.

    On the commit being captured from there is no optimizer at all: the fit is
    BFGS and nothing else, which is exactly the number this gate anchors to.
    """
    extra = {}
    if optimizer is not None and "optimizer" in inspect.signature(
        fit_mod.evaluate_body_grouped
    ).parameters:
        extra["optimizer"] = optimizer
    return fit_mod.evaluate_body_grouped(**kwargs, **extra)


def capture() -> dict:
    """Fit every case with plain BFGS and emit the hex-float record."""
    return {name: _payload(_run(kw, "bfgs")) for name, kw in _cases().items()}


# ------------------------------------------------------------------- the checks

def _anchor_failures(golden: dict) -> list[str]:
    """Tie the golden file to the anchor S0b already checked in.

    Two records of the same fit that can drift apart are worse than one, so the
    exp case is compared against ``TestNoPathIsUnchanged``'s constants rather
    than being an independent second opinion about them.
    """
    from tests.integrations.llmsr.test_progress import TestNoPathIsUnchanged as Anchor

    case = golden.get("exp-2group", {})
    out = []
    if case.get("score") != Anchor.GOLD_SCORE:
        out.append(
            f"exp-2group score {case.get('score')} != anchor {Anchor.GOLD_SCORE}"
        )
    for label, params in Anchor.GOLD_PARAMS.items():
        got = case.get("params_per_group", {}).get(label)
        if got != params:
            out.append(f"exp-2group params[{label}] {got} != anchor {params}")
    return out


def check_all() -> list[str]:
    """Every parity failure, as human-readable lines. Empty means identical."""
    golden = json.loads(GOLDEN.read_text())
    failures = _anchor_failures(golden)
    for name, kwargs in _cases().items():
        want = golden.get(name)
        if want is None:
            failures.append(f"{name}: no golden record (regenerate the golden file)")
            continue

        got = _payload(_run(kwargs, "bfgs"))
        if got != want:
            failures.append(f"{name}: --optimizer bfgs drifted from main\n"
                            f"  want {json.dumps(want, sort_keys=True)}\n"
                            f"  got  {json.dumps(got, sort_keys=True)}")

        auto = _run(kwargs, "auto")
        used = set(getattr(auto, "optimizer_per_group", {}).values())
        if used != {"bfgs"}:
            # Not a parity failure but a failure of the case to be ABOUT parity:
            # this gate only claims identity where BFGS moved, so a case that
            # escalated is not evidence for that claim and must not pose as it.
            failures.append(
                f"{name}: auto reported {sorted(used)}, so BFGS did not move here; "
                "this case cannot anchor the moved-path parity claim"
            )
        elif _payload(auto) != want:
            failures.append(f"{name}: auto drifted from main where BFGS moved\n"
                            f"  want {json.dumps(want, sort_keys=True)}\n"
                            f"  got  {json.dumps(_payload(auto), sort_keys=True)}")
    return failures


def main(argv: list[str]) -> int:
    mode = argv[1] if len(argv) > 1 else "check"
    if mode == "capture":
        print(json.dumps(capture(), indent=2, sort_keys=True))
        return 0
    if mode != "check":
        print(f"usage: {argv[0]} capture|check", file=sys.stderr)
        return 2
    failures = check_all()
    for line in failures:
        print(f"FAIL {line}")
    if failures:
        return 1
    print(f"OK  {len(_cases())} cases bit-for-bit identical to main")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
