#!/usr/bin/env python3
"""Strictly certify this checkout as a Wheeler Codex development environment.

Run from the repository root through the locked development environment:

    uv run --frozen --extra dev python scripts/certify-codex-dev.py

The command deliberately has no "skip E2E" mode. A successful result means the
project skills are visible to Codex, the editable checkout owns the MCP surface,
Neo4j accepted an authenticated query, and every collected E2E test passed.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import subprocess
import sys
import tempfile
import tomllib
import xml.etree.ElementTree as ET
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

import yaml


EXPECTED_SKILLS = 39
EXPECTED_SERVERS = {
    "wheeler_core": 14,
    "wheeler_query": 11,
    "wheeler_mutations": 18,
    "wheeler_ops": 10,
}
SERVER_MODULES = {
    "wheeler_core": "wheeler.mcp_core",
    "wheeler_query": "wheeler.mcp_query",
    "wheeler_mutations": "wheeler.mcp_mutations",
    "wheeler_ops": "wheeler.mcp_ops",
}
EXPECTED_TOOLS = 53
GENERATED_CONFIG_MARKER = "# Generated by scripts/configure-codex-dev.py."
NEO4J_ENV_DEFAULTS = {
    "NEO4J_URI": "bolt://localhost:7687",
    "NEO4J_USERNAME": "neo4j",
    "NEO4J_PASSWORD": "research-graph",
    "NEO4J_DATABASE": "neo4j",
}


class CertificationError(RuntimeError):
    """A required development-environment invariant was not met."""


@dataclass(frozen=True)
class E2EResult:
    tests: int
    passed: int
    failures: int
    errors: int
    skipped: int


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def verify_editable_checkout(root: Path) -> str:
    """Require Wheeler to resolve to this source tree, not an installed wheel."""
    import wheeler

    package_file = Path(wheeler.__file__).resolve()
    source_tree = (root / "wheeler").resolve()
    try:
        package_file.relative_to(source_tree)
    except ValueError as exc:
        raise CertificationError(
            f"Wheeler imports from {package_file}, not this checkout. "
            "Run the command with `uv run --frozen --extra dev`."
        ) from exc
    return str(package_file)


def _skill_names(directory: Path) -> set[str]:
    return {path.parent.name for path in directory.glob("*/SKILL.md") if path.is_file()}


def _validate_skill_frontmatter(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise CertificationError(f"Skill frontmatter must open {path}")
    try:
        closing = lines.index("---", 1)
        metadata = yaml.safe_load("\n".join(lines[1:closing]))
    except (ValueError, yaml.YAMLError) as exc:
        raise CertificationError(f"Invalid skill frontmatter: {path}") from exc
    if not isinstance(metadata, dict):
        raise CertificationError(f"Skill frontmatter is not a mapping: {path}")
    expected_name = path.parent.name
    if metadata.get("name") != expected_name:
        raise CertificationError(
            f"Skill {path} has name {metadata.get('name')!r}, expected {expected_name!r}"
        )
    description = metadata.get("description")
    if not isinstance(description, str) or not description.strip():
        raise CertificationError(f"Skill {path} has no non-empty description")


def verify_project_skills(root: Path) -> set[str]:
    """Verify Codex sees the canonical 39 project skills through .agents/skills."""
    canonical = root / "skills"
    visible = root / ".agents" / "skills"
    if not visible.is_dir():
        raise CertificationError(f"Codex project skills are unavailable: missing {visible}")

    canonical_names = _skill_names(canonical)
    visible_names = _skill_names(visible)
    if len(canonical_names) != EXPECTED_SKILLS:
        raise CertificationError(
            f"Canonical skill tree has {len(canonical_names)} skills, expected {EXPECTED_SKILLS}"
        )
    if visible_names != canonical_names:
        missing = sorted(canonical_names - visible_names)
        extra = sorted(visible_names - canonical_names)
        raise CertificationError(
            f"Codex skill surface differs from skills/ (missing={missing}, extra={extra})"
        )
    if not os.path.samefile(visible, canonical):
        raise CertificationError(
            ".agents/skills is a separate copy. Re-run the project configurator "
            "to create a symlink or Windows junction to skills/."
        )
    for skill_file in sorted(visible.glob("*/SKILL.md")):
        _validate_skill_frontmatter(skill_file)
    return visible_names


def _generated_servers(config_path: Path) -> dict[str, dict[str, Any]]:
    try:
        text = config_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise CertificationError(f"Cannot read generated Codex config: {config_path}") from exc
    if not text.startswith(GENERATED_CONFIG_MARKER):
        raise CertificationError(
            f"{config_path} is not generated project wiring; run configure-codex-dev.py"
        )
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise CertificationError(f"Generated Codex config is invalid TOML: {config_path}") from exc
    servers = data.get("mcp_servers")
    if not isinstance(servers, dict):
        raise CertificationError(f"No mcp_servers table in {config_path}")
    if set(servers) != set(EXPECTED_SERVERS):
        raise CertificationError(
            f"Configured MCP servers are {sorted(servers)}, expected {sorted(EXPECTED_SERVERS)}"
        )
    return servers


def _validate_generated_command(
    server_name: str,
    command: str,
    args: list[str],
    project_root: Path,
    *,
    wsl_mapper: Callable[[str, list[str], Path], str] | None = None,
) -> None:
    if "uvx" in Path(command).name.lower() or any("uvx" in Path(arg).name.lower() for arg in args):
        raise CertificationError(f"{server_name} launches uvx instead of the editable checkout")
    try:
        run_index = args.index("run")
    except ValueError as exc:
        raise CertificationError(f"{server_name} does not launch with uv run") from exc
    expected_tail = [
        "run",
        "--frozen",
        "--project",
        args[run_index + 3] if len(args) > run_index + 3 else "",
        "python",
        "-m",
        SERVER_MODULES[server_name],
    ]
    if not expected_tail[3] or args[run_index:] != expected_tail:
        raise CertificationError(
            f"{server_name} does not use the exact editable uv run command"
        )
    configured_project = expected_tail[3]
    is_windows_wsl = os.name == "nt" and Path(command).name.lower() in {"wsl", "wsl.exe"}
    if is_windows_wsl:
        mapper = wsl_mapper or _map_project_into_wsl
        actual_project = mapper(command, args, project_root)
        matches = PurePosixPath(actual_project) == PurePosixPath(configured_project)
    else:
        matches = os.path.normcase(str(Path(configured_project).resolve())) == os.path.normcase(
            str(project_root.resolve())
        )
    if not matches:
        raise CertificationError(
            f"{server_name} --project points to a different checkout; rerun the configurator"
        )


def _map_project_into_wsl(command: str, args: list[str], project_root: Path) -> str:
    try:
        exec_index = args.index("--exec")
        completed = subprocess.run(
            [command, *args[:exec_index], "--exec", "wslpath", "-a", str(project_root)],
            check=True,
            capture_output=True,
            text=True,
            timeout=20,
        )
    except (ValueError, OSError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        raise CertificationError("Could not map the current checkout into WSL") from exc
    mapped = completed.stdout.strip()
    if not mapped:
        raise CertificationError("WSL returned an empty checkout path")
    return mapped


def _mcp_environment(neo4j_env: dict[str, str]) -> dict[str, str]:
    environment = os.environ.copy()
    environment.update(neo4j_env)
    existing = environment.get("WSLENV", "").split(":")
    forwarded = [name for name in neo4j_env if name not in existing]
    environment["WSLENV"] = ":".join(filter(None, (*existing, *forwarded)))
    return environment


async def _probe_mcp_server(
    command: str,
    args: list[str],
    *,
    call_start: bool,
    environment: dict[str, str],
) -> tuple[set[str], dict[str, Any] | None, dict[str, Any] | None]:
    """Connect over stdio using the exact command Codex will launch."""
    import json

    from mcp import ClientSession, StdioServerParameters
    from mcp.client.stdio import stdio_client

    parameters = StdioServerParameters(command=command, args=args, env=environment)
    async with stdio_client(parameters) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            names = {tool.name for tool in (await session.list_tools()).tools}
            if not call_start:
                return names, None, None
            response = await session.call_tool("get_act", {"name": "start", "host": "codex"})
            if response.isError:
                raise CertificationError("get_act(start, host=codex) returned an MCP error")
            act = response.structuredContent
            if not isinstance(act, dict):
                for item in response.content:
                    text = getattr(item, "text", "")
                    if text:
                        act = json.loads(text)
                        break
            query_response = await session.call_tool(
                "run_cypher", {"query": "RETURN 1 AS value"}
            )
            if query_response.isError:
                raise CertificationError("Neo4j RETURN 1 returned an MCP error")
            query_result = query_response.structuredContent
            if not isinstance(query_result, dict):
                for item in query_response.content:
                    text = getattr(item, "text", "")
                    if text:
                        query_result = json.loads(text)
                        break
            return (
                names,
                act if isinstance(act, dict) else None,
                query_result if isinstance(query_result, dict) else None,
            )


def _verify_neo4j_result(result: dict[str, Any] | None) -> None:
    result = result or {}
    if isinstance(result.get("result"), dict):
        result = result["result"]
    rows = result.get("results")
    if result.get("error") or result.get("count") != 1 or rows != [{"value": 1}]:
        raise CertificationError(
            "Authenticated Neo4j RETURN 1 failed through the generated core MCP server"
        )


async def verify_mcp_surface(
    config_path: Path,
    *,
    neo4j_env: dict[str, str],
    probe: Callable[..., Any] = _probe_mcp_server,
) -> dict[str, set[str]]:
    """Launch the generated MCP commands and verify the exact split surface."""
    servers = _generated_servers(config_path)
    surfaces: dict[str, set[str]] = {}
    owner: dict[str, str] = {}
    duplicates: list[str] = []
    start_act: dict[str, Any] | None = None
    neo4j_result: dict[str, Any] | None = None
    environment = _mcp_environment(neo4j_env)

    for server_name, expected in EXPECTED_SERVERS.items():
        entry = servers[server_name]
        if entry.get("enabled") is not True:
            raise CertificationError(f"{server_name} is not enabled")
        command = entry.get("command")
        args = entry.get("args")
        if not isinstance(command, str) or not isinstance(args, list) or not all(
            isinstance(arg, str) for arg in args
        ):
            raise CertificationError(f"{server_name} has an invalid command or args")
        _validate_generated_command(server_name, command, args, config_path.parents[1])
        timeout = float(entry.get("startup_timeout_sec", 60)) + float(
            entry.get("tool_timeout_sec", 120)
        )
        try:
            names, act, query_result = await asyncio.wait_for(
                probe(
                    command,
                    args,
                    call_start=server_name == "wheeler_core",
                    environment=environment,
                ),
                timeout=timeout,
            )
        except CertificationError:
            raise
        except TimeoutError as exc:
            raise CertificationError(f"{server_name} MCP launch timed out") from exc
        except Exception as exc:
            raise CertificationError(
                f"{server_name} MCP launch failed ({type(exc).__name__})"
            ) from exc
        if act is not None:
            start_act = act
        if query_result is not None:
            neo4j_result = query_result
        if len(names) != expected:
            raise CertificationError(
                f"{server_name} exposes {len(names)} tools, expected {expected}"
            )
        surfaces[server_name] = names
        for name in names:
            if name in owner:
                duplicates.append(f"{name} ({owner[name]}, {server_name})")
            owner[name] = server_name

    if duplicates:
        raise CertificationError("Duplicate MCP tools: " + ", ".join(sorted(duplicates)))
    if len(owner) != EXPECTED_TOOLS:
        raise CertificationError(f"MCP surface has {len(owner)} tools, expected {EXPECTED_TOOLS}")

    act = start_act or {}
    if (
        act.get("error")
        or act.get("name") != "wh:start"
        or act.get("host") != "codex"
        or not str(act.get("body", "")).strip()
    ):
        raise CertificationError("get_act('start', host='codex') returned an invalid act")
    _verify_neo4j_result(neo4j_result)
    return surfaces


def local_neo4j_environment() -> dict[str, str]:
    """Resolve the local dev database without consulting a possibly remote keychain."""
    resolved = {
        name: os.environ.get(name, default) for name, default in NEO4J_ENV_DEFAULTS.items()
    }
    resolved["WHEELER_NO_KEYCHAIN"] = "1"
    return resolved


def _junit_totals(report: Path) -> E2EResult:
    root = ET.parse(report).getroot()
    suites = [root] if root.tag == "testsuite" else list(root.findall("testsuite"))
    if not suites:
        raise CertificationError("E2E pytest produced no JUnit test suites")

    def total(attribute: str) -> int:
        return sum(int(suite.attrib.get(attribute, "0")) for suite in suites)

    tests = total("tests")
    failures = total("failures")
    errors = total("errors")
    skipped = total("skipped")
    return E2EResult(
        tests=tests,
        passed=tests - failures - errors - skipped,
        failures=failures,
        errors=errors,
        skipped=skipped,
    )


def _redact(text: str, secrets: Sequence[str]) -> str:
    for secret in secrets:
        if secret:
            text = text.replace(secret, "[REDACTED]")
    return text


def run_e2e(
    root: Path,
    *,
    launcher: dict[str, Any],
    secrets: Sequence[str] = (),
    environment: dict[str, str] | None = None,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
) -> E2EResult:
    """Run real E2E tests and reject empty, skipped, failed, or errored runs."""
    target = root / "tests" / "e2e"
    temp_root = root / ".wheeler"
    temp_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="certify-", dir=temp_root) as temp_dir:
        report = Path(temp_dir) / "e2e.xml"
        launcher_command = launcher["command"]
        launcher_args = list(launcher["args"])
        run_index = launcher_args.index("run")
        launcher_project = launcher_args[run_index + 3]
        is_windows_wsl = Path(launcher_command).name.lower() in {"wsl", "wsl.exe"}
        if is_windows_wsl:
            relative_target = target.resolve().relative_to(root.resolve()).as_posix()
            remote_target = str(PurePosixPath(launcher_project) / relative_target)
            relative_report = report.resolve().relative_to(root.resolve()).as_posix()
            remote_report = str(PurePosixPath(launcher_project) / relative_report)
        else:
            remote_target = str(target)
            remote_report = str(report)
        command = [
            launcher_command,
            *launcher_args[:run_index],
            "run",
            "--frozen",
            "--extra",
            "dev",
            "--project",
            launcher_project,
            "python",
            "-m",
            "pytest",
            remote_target,
            "-q",
            "--disable-warnings",
            f"--junitxml={remote_report}",
        ]
        child_environment = _mcp_environment(environment or {})
        completed = runner(
            command,
            cwd=root,
            env=child_environment,
            text=True,
            capture_output=True,
            check=False,
        )
        if not report.is_file():
            output = _redact((completed.stdout or "") + (completed.stderr or ""), secrets)
            tail = "\n".join(output.splitlines()[-20:])
            raise CertificationError(
                f"E2E pytest exited {completed.returncode} without a JUnit report\n{tail}"
            )
        result = _junit_totals(report)
        if (
            completed.returncode != 0
            or result.tests == 0
            or result.failures
            or result.errors
            or result.skipped
            or result.passed != result.tests
        ):
            output = _redact((completed.stdout or "") + (completed.stderr or ""), secrets)
            tail = "\n".join(output.splitlines()[-20:])
            raise CertificationError(
                "E2E certification requires every collected test to pass: "
                f"tests={result.tests}, passed={result.passed}, failures={result.failures}, "
                f"errors={result.errors}, skipped={result.skipped}, exit={completed.returncode}\n"
                f"{tail}"
            )
    return result


def _parser() -> argparse.ArgumentParser:
    return argparse.ArgumentParser(description=__doc__)


def main(argv: Sequence[str] | None = None) -> int:
    _parser().parse_args(argv)
    root = project_root()
    os.chdir(root)

    try:
        checkout = verify_editable_checkout(root)
        print(f"PASS editable checkout: {checkout}")
        skills = verify_project_skills(root)
        print(f"PASS Codex project skills: {len(skills)}")
        neo4j_env = local_neo4j_environment()
        servers = _generated_servers(root / ".codex" / "config.toml")
        surfaces = asyncio.run(
            verify_mcp_surface(
                root / ".codex" / "config.toml",
                neo4j_env=neo4j_env,
            )
        )
        counts = ", ".join(
            f"{name.removeprefix('wheeler_')}={len(tools)}"
            for name, tools in surfaces.items()
        )
        print(f"PASS MCP surface: {EXPECTED_TOOLS} ({counts}) and get_act(start, host=codex)")
        print("PASS Neo4j: generated core MCP authenticated and returned 1")
        e2e = run_e2e(
            root,
            launcher=servers["wheeler_core"],
            secrets=(neo4j_env["NEO4J_PASSWORD"],),
            environment=neo4j_env,
        )
        print(f"PASS real E2E: {e2e.passed}/{e2e.tests} passed, 0 skipped")
    except CertificationError as exc:
        print(f"FAIL certification: {exc}", file=sys.stderr)
        return 1

    print("CERTIFIED Wheeler Codex development environment")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
