#!/usr/bin/env python3
"""Generate project-local Codex wiring for Wheeler development.

The generated files are deliberately machine-specific and ignored by Git.  MCP
servers run the current checkout with ``uv run --frozen`` so tests never fall
back to the released Wheeler package used by the distributable plugin.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import shutil
import stat
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence


SERVER_MODULES = {
    "wheeler_core": "wheeler.mcp_core",
    "wheeler_query": "wheeler.mcp_query",
    "wheeler_mutations": "wheeler.mcp_mutations",
    "wheeler_ops": "wheeler.mcp_ops",
}
GENERATED_MARKER = "# Generated by scripts/configure-codex-dev.py."
LOCAL_EXCLUDES = ("/.agents/", "/.codex/")


class ConfigurationError(RuntimeError):
    """Raised when safe project-local configuration is not possible."""


@dataclass(frozen=True)
class Launcher:
    command: str
    prefix_args: tuple[str, ...]
    project_root: str


def _wsl_environment(home: str, project_root: str) -> str:
    checkout_id = hashlib.sha256(project_root.encode("utf-8")).hexdigest()[:12]
    return f"{home.rstrip('/')}/.cache/wheeler/codex-dev/{checkout_id}"


def detect_host(
    *,
    system: str | None = None,
    environ: Mapping[str, str] | None = None,
    proc_version: str | None = None,
) -> str:
    """Return ``windows``, ``wsl``, ``macos``, or ``linux``."""
    system = system or platform.system()
    if environ is None:
        environ = os.environ
    if system == "Windows":
        return "windows"
    if system == "Darwin":
        return "macos"
    if system == "Linux":
        if environ.get("WSL_DISTRO_NAME") or environ.get("WSL_INTEROP"):
            return "wsl"
        if proc_version is None:
            try:
                proc_version = Path("/proc/version").read_text(encoding="utf-8")
            except OSError:
                proc_version = ""
        if "microsoft" in proc_version.lower():
            return "wsl"
        return "linux"
    raise ConfigurationError(f"Unsupported operating system: {system}")


def _run_text(argv: Sequence[str]) -> str:
    try:
        result = subprocess.run(
            argv,
            check=True,
            capture_output=True,
            text=True,
            timeout=20,
        )
    except (OSError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        raise ConfigurationError(f"Command failed: {argv[0]}: {exc}") from exc
    return result.stdout.strip()


def _try_run_text(argv: Sequence[str]) -> str:
    try:
        return _run_text(argv)
    except ConfigurationError:
        return ""


def _native_launcher(project_root: Path, host: str, uv: str | None) -> Launcher:
    uv_command = uv or shutil.which("uv")
    if not uv_command and host == "wsl":
        candidates = [
            Path.home() / ".local" / "bin" / "uv",
            Path.home() / ".cargo" / "bin" / "uv",
            Path.home() / ".linuxbrew" / "bin" / "uv",
            Path("/home/linuxbrew/.linuxbrew/bin/uv"),
            Path("/usr/local/bin/uv"),
            Path("/usr/bin/uv"),
        ]
        uv_command = next(
            (str(candidate) for candidate in candidates if os.access(candidate, os.X_OK)),
            None,
        )
    if not uv_command:
        raise ConfigurationError(
            "uv was not found on PATH. Install uv or pass its path with --uv."
        )
    uv_command = str(Path(uv_command).expanduser().resolve())
    if host == "wsl":
        environment = _wsl_environment(str(Path.home()), str(project_root))
        return Launcher(
            command="/usr/bin/env",
            prefix_args=(f"UV_PROJECT_ENVIRONMENT={environment}", uv_command),
            project_root=str(project_root),
        )
    return Launcher(uv_command, (), str(project_root))


def _windows_wsl_launcher(
    project_root: Path,
    *,
    uv: str | None,
    distro: str | None,
    wsl_command: str | None = None,
) -> Launcher:
    wsl = wsl_command or shutil.which("wsl.exe") or shutil.which("wsl")
    if not wsl:
        raise ConfigurationError("WSL was requested, but wsl.exe was not found on PATH.")
    wsl = str(Path(wsl).resolve())
    distro_args: tuple[str, ...] = ("-d", distro) if distro else ()
    if not distro:
        distro = _run_text((wsl, "--exec", "sh", "-lc", "printf %s \"$WSL_DISTRO_NAME\""))
        distro_args = ("-d", distro) if distro else ()
    linux_root = _run_text(
        (wsl, *distro_args, "--exec", "wslpath", "-a", str(project_root))
    )
    linux_home = _run_text(
        (wsl, *distro_args, "--exec", "sh", "-lc", "printf %s \"$HOME\"")
    )
    if not linux_home.startswith("/"):
        raise ConfigurationError("Could not resolve the selected WSL user's home directory.")
    linux_uv = uv or _try_run_text(
        (wsl, *distro_args, "--exec", "sh", "-lc", "command -v uv")
    )
    if not linux_uv:
        # Homebrew's WSL prefix is often absent from non-interactive PATH. Probe
        # only this user and exact trusted installation locations, never another
        # user's home or a broad filesystem search.
        candidates = (
            f"{linux_home}/.local/bin/uv",
            f"{linux_home}/.cargo/bin/uv",
            f"{linux_home}/.linuxbrew/bin/uv",
            "/home/linuxbrew/.linuxbrew/bin/uv",
            "/usr/local/bin/uv",
            "/usr/bin/uv",
        )
        linux_uv = _try_run_text(
            (
                wsl,
                *distro_args,
                "--exec",
                "sh",
                "-c",
                "for candidate do if [ -x \"$candidate\" ]; then printf %s \"$candidate\"; exit 0; fi; done; exit 1",
                "wheeler-uv-probe",
                *candidates,
            )
        )
    if not linux_uv:
        raise ConfigurationError("uv was not found in the selected WSL distribution.")
    environment = _wsl_environment(linux_home, linux_root)
    return Launcher(
        command=wsl,
        prefix_args=(
            *distro_args,
            "--exec",
            "/usr/bin/env",
            f"UV_PROJECT_ENVIRONMENT={environment}",
            linux_uv,
        ),
        project_root=linux_root,
    )


def resolve_launcher(
    project_root: Path,
    *,
    host: str,
    uv: str | None = None,
    wsl_distro: str | None = None,
    wsl_command: str | None = None,
    actual_system: str | None = None,
) -> Launcher:
    """Resolve an absolute, shell-free launcher for the selected host."""
    actual_system = actual_system or platform.system()
    selected = detect_host(system=actual_system) if host == "auto" else host

    if actual_system == "Windows" and selected == "windows":
        native_uv = uv or shutil.which("uv")
        if native_uv:
            return _native_launcher(project_root, "windows", native_uv)
        return _windows_wsl_launcher(
            project_root,
            uv=None,
            distro=wsl_distro,
            wsl_command=wsl_command,
        )
    if actual_system == "Windows" and selected == "wsl":
        return _windows_wsl_launcher(
            project_root,
            uv=uv,
            distro=wsl_distro,
            wsl_command=wsl_command,
        )
    if selected in {"linux", "macos", "wsl"}:
        return _native_launcher(project_root, selected, uv)
    if selected == "windows":
        raise ConfigurationError("The Windows target can only be generated on Windows.")
    raise ConfigurationError(f"Unsupported host selection: {selected}")


def _toml(value: str) -> str:
    # JSON strings are valid TOML basic strings and handle Windows paths safely.
    return json.dumps(value, ensure_ascii=False)


def render_config(launcher: Launcher) -> str:
    lines = [
        GENERATED_MARKER,
        "# Machine-specific paths stay local; rerun this script after moving the checkout.",
        "# Authentication is read by Wheeler at runtime. No credentials are stored here.",
        "",
    ]
    for server, module in SERVER_MODULES.items():
        args = (
            *launcher.prefix_args,
            "run",
            "--frozen",
            "--project",
            launcher.project_root,
            "python",
            "-m",
            module,
        )
        rendered_args = ", ".join(_toml(arg) for arg in args)
        lines.extend(
            [
                f"[mcp_servers.{server}]",
                f"command = {_toml(launcher.command)}",
                f"args = [{rendered_args}]",
                "enabled = true",
                "startup_timeout_sec = 60",
                "tool_timeout_sec = 120",
                "",
            ]
        )
    return "\n".join(lines)


def _is_reparse_point(path: Path) -> bool:
    try:
        attributes = path.lstat().st_file_attributes
    except (AttributeError, OSError):
        return path.is_symlink()
    return bool(attributes & stat.FILE_ATTRIBUTE_REPARSE_POINT)


def ensure_skill_link(project_root: Path, *, force: bool, dry_run: bool) -> str:
    source = project_root / "skills"
    link = project_root / ".agents" / "skills"
    if not source.is_dir():
        raise ConfigurationError(f"Wheeler skills directory not found: {source}")

    if link.exists() or link.is_symlink() or _is_reparse_point(link):
        try:
            if link.resolve() == source.resolve():
                return "kept existing .agents/skills link"
        except OSError:
            pass
        if not force:
            raise ConfigurationError(
                f"{link} already exists and does not point to {source}; use --force to replace a link"
            )
        if not (link.is_symlink() or _is_reparse_point(link)):
            raise ConfigurationError(f"Refusing to replace real directory or file: {link}")
        if not dry_run:
            if link.is_dir():
                os.rmdir(link)
            else:
                link.unlink()

    if dry_run:
        return "would create .agents/skills link"
    link.parent.mkdir(parents=True, exist_ok=True)
    if os.name == "nt":
        subprocess.run(
            ["cmd.exe", "/d", "/c", "mklink", "/J", str(link), str(source)],
            check=True,
            capture_output=True,
            text=True,
        )
    else:
        link.symlink_to(Path("..") / "skills", target_is_directory=True)
    return "created .agents/skills link"


def resolve_git_exclude(project_root: Path) -> Path:
    """Resolve Git's exclude file, including for linked worktrees."""
    raw_path = _run_text(
        ("git", "-C", str(project_root), "rev-parse", "--git-path", "info/exclude")
    )
    if not raw_path:
        raise ConfigurationError("Git returned an empty path for info/exclude.")
    exclude = Path(raw_path)
    if not exclude.is_absolute():
        exclude = project_root / exclude
    try:
        return exclude.resolve(strict=False)
    except OSError as exc:
        raise ConfigurationError(f"Could not resolve Git exclude path: {exclude}") from exc


def ensure_git_excludes(exclude: Path, *, dry_run: bool) -> str:
    existing = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    present = {line.strip() for line in existing.splitlines()}
    missing = [item for item in LOCAL_EXCLUDES if item not in present]
    if not missing:
        return "kept existing Git excludes"
    if dry_run:
        return "would add project-local Git excludes"
    separator = "" if not existing or existing.endswith("\n") else "\n"
    addition = "# Local Codex development wiring (machine-specific; do not commit).\n"
    addition += "\n".join(missing) + "\n"
    exclude.parent.mkdir(parents=True, exist_ok=True)
    with exclude.open("a", encoding="utf-8", newline="\n") as handle:
        handle.write(separator + addition)
    return "added project-local Git excludes"


def write_config(
    project_root: Path, content: str, *, force: bool, dry_run: bool
) -> str:
    destination = project_root / ".codex" / "config.toml"
    if destination.exists():
        existing = destination.read_text(encoding="utf-8")
        if existing == content:
            return "kept current .codex/config.toml"
        if not force and not existing.startswith(GENERATED_MARKER):
            raise ConfigurationError(
                f"Refusing to overwrite hand-written configuration: {destination}. Use --force to replace it."
            )
        if not force:
            raise ConfigurationError(
                f"Generated configuration has local changes: {destination}. Use --force to replace it."
            )
    if dry_run:
        return "would write .codex/config.toml"
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(".toml.tmp")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    temporary.replace(destination)
    return "wrote .codex/config.toml"


def configure(
    project_root: Path,
    *,
    host: str,
    uv: str | None,
    wsl_distro: str | None,
    force: bool,
    dry_run: bool,
) -> list[str]:
    project_root = project_root.expanduser().resolve()
    if not (project_root / "pyproject.toml").is_file():
        raise ConfigurationError(f"Not a Wheeler checkout: {project_root}")
    launcher = resolve_launcher(
        project_root, host=host, uv=uv, wsl_distro=wsl_distro
    )
    # Check every conflict before changing either local integration point.
    content = render_config(launcher)
    destination = project_root / ".codex" / "config.toml"
    if destination.exists() and destination.read_text(encoding="utf-8") != content and not force:
        raise ConfigurationError(
            f"Existing configuration differs: {destination}. Re-run with --force after reviewing it."
        )
    exclude = resolve_git_exclude(project_root)
    return [
        ensure_skill_link(project_root, force=force, dry_run=dry_run),
        ensure_git_excludes(exclude, dry_run=dry_run),
        write_config(project_root, content, force=force, dry_run=dry_run),
    ]


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Wheeler checkout to configure (defaults to this script's checkout)",
    )
    parser.add_argument(
        "--host",
        choices=("auto", "windows", "wsl", "macos", "linux"),
        default="auto",
        help="Launcher environment (auto detects the current host)",
    )
    parser.add_argument("--uv", help="Absolute uv path in the selected environment")
    parser.add_argument("--wsl-distro", help="WSL distribution to use from Windows")
    parser.add_argument("--force", action="store_true", help="Replace generated local wiring")
    parser.add_argument("--dry-run", action="store_true", help="Show actions without writing")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        actions = configure(
            args.project_root,
            host=args.host,
            uv=args.uv,
            wsl_distro=args.wsl_distro,
            force=args.force,
            dry_run=args.dry_run,
        )
    except ConfigurationError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    for action in actions:
        print(action)
    print("Restart Codex in this project to load the generated skills and MCP servers.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
