"""Marshal-out (deterministic): register a service's raw output file as a node.

Every service output is an artifact. The raw ``-o`` JSON dump a service writes
is itself a first-class graph node, so every node parsed out of it can chain
back through it to the run Execution. This closes the output end of the
sandwich: ``Artifact WAS_GENERATED_BY Execution`` and each generated node
``WAS_DERIVED_FROM`` the artifact.

This module is a marshal-out caller: it imports ``execute_tool`` lazily
(function-local), mirroring ``wheeler/validation/ledger.py`` and ``ingest.py``.
Every graph write routes through ``execute_tool`` so the triple-write, write
receipt, trace id, and embedding wiring all fire. Edge creation reuses the
``_link_once`` / ``_edge_exists`` helpers in ``ingest.py`` so re-registering
the same artifact never duplicates the ``WAS_GENERATED_BY`` edge.

Invariants:
  - Best-effort. ANY failure returns ``None`` and logs a warning, never raises:
    a failed artifact registration must not break the surrounding ingest.
  - Sequential writes only. Never ``asyncio.gather``: ``execute_tool`` reuses
    one cached backend singleton and Neo4j forbids concurrent queries.
  - link_once. The ``WAS_GENERATED_BY`` edge is guarded by an existence check
    because the backend's ``create_relationship`` is a bare CREATE.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from wheeler.config import WheelerConfig

from .ingest import _link_once

logger = logging.getLogger(__name__)


async def register_output_artifact(
    path: str | None,
    *,
    execution_id: str,
    service: str,
    config: WheelerConfig,
    description: str = "",
) -> str | None:
    """Register a service's raw output file as a Dataset node, linked to its run.

    The raw ``-o`` JSON results dump is registered via ``ensure_artifact`` as a
    Dataset (the data bucket: a results dump is data, not a Document or Script),
    tagged with ``service``, and linked ``-[WAS_GENERATED_BY]->`` the run
    Execution. The artifact node id is returned so the caller can link each
    generated node ``WAS_DERIVED_FROM`` it.

    Args:
        path: Path to the raw output file. ``None`` or a missing file is a
            no-op that returns ``None``.
        execution_id: The run Execution node id the artifact was generated by.
        service: The provider:service tag (e.g. ``asta:paper-finder``).
        config: Active Wheeler config.
        description: Human description for the Dataset node. Falls back to a
            service-derived default when empty.

    Returns:
        The artifact node id on success, or ``None`` on any failure (best-effort).
    """
    if not path:
        return None
    abs_path = Path(path)
    if not abs_path.exists():
        logger.warning(
            "register_output_artifact: output file not found, skipping: %s", path,
        )
        return None

    desc = description or f"{service} raw output"

    try:
        from wheeler.tools.graph_tools import _get_backend, execute_tool

        backend = await _get_backend(config)

        # Register the raw .json results dump as a Dataset (the data bucket).
        # ensure_artifact's extension map has no rule for .json, so it would
        # default to Document; passing artifact_type="dataset" routes it to the
        # Dataset label (override_map in _detect_artifact_type). ensure_artifact
        # is idempotent on path, so re-registering the same file is a no-op.
        ensure_result_str = await execute_tool(
            "ensure_artifact",
            {
                "path": str(abs_path),
                "artifact_type": "dataset",
                "description": desc,
                "service": service,
                "tier": "generated",
            },
            config,
        )
        ensure_result = json.loads(ensure_result_str)
        if "error" in ensure_result:
            logger.warning(
                "register_output_artifact: ensure_artifact failed for %s: %s",
                path, ensure_result,
            )
            return None
        artifact_id = ensure_result.get("node_id")
        if not artifact_id:
            logger.warning(
                "register_output_artifact: ensure_artifact returned no node_id for %s",
                path,
            )
            return None

        # ensure_artifact delegates to add_dataset but does not forward the
        # service tag, so stamp it explicitly via update_node (best-effort).
        # service is a first-class NodeBase field, so update_node's allow-list
        # (derived from model_fields) accepts it.
        if service:
            try:
                update_result_str = await execute_tool(
                    "update_node",
                    {"node_id": artifact_id, "service": service},
                    config,
                )
                update_result = json.loads(update_result_str)
                if "error" in update_result:
                    logger.warning(
                        "register_output_artifact: service-tag update failed for %s: %s",
                        artifact_id, update_result,
                    )
            except Exception:
                logger.warning(
                    "register_output_artifact: service-tag update raised for %s",
                    artifact_id, exc_info=True,
                )

        # Provenance: Artifact WAS_GENERATED_BY the run Execution (link_once).
        if execution_id:
            await _link_once(
                backend, config, artifact_id, "WAS_GENERATED_BY", execution_id,
            )

        logger.info(
            "register_output_artifact: registered %s as %s (service=%s)",
            path, artifact_id, service,
        )
        return artifact_id
    except Exception:
        logger.warning(
            "register_output_artifact: failed for %s (best-effort)",
            path, exc_info=True,
        )
        return None
